blank_issues_enabled: true
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/sehmaluva/hacktoberfest/discussions
    about: Ask questions, start discussions, and connect with the community
  - name: 🎯 Hacktoberfest Official Site
    url: https://hacktoberfest.com
    about: Learn more about Hacktoberfest and how to participate
  - name: 📖 Contributing Guidelines
    url: https://github.com/sehmaluva/hacktoberfest/blob/main/CONTRIBUTING.md
    about: Read our detailed contribution guidelines before getting started